# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ehsan_home_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ast import For
from msilib.schema import Class
from PyQt5 import QtCore, QtGui, QtWidgets
from investor import InvestorList,InvestorForm
from PyQt5.QtWidgets import QMainWindow,QMenu,QMenuBar,QAction
import home
from payment import PaymentListForCurrentPeriod,PaymentListForAll
from assets import AssetBasketList,AssetForm,AssetList,AssetPeriodAmountList
from period import PeriodList
from wallet import WalletList
class EhsanFrame(QMainWindow):
    def __init__(self):
        super(EhsanFrame,self).__init__()
        self.setObjectName("Ehsan Fund Home")
        self.resize(1000, 800)

        """     self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.container = QtWidgets.QWidget(self.centralwidget)
        self.container.setGeometry(QtCore.QRect(19, 19, 761, 521))
        self.container.setObjectName("container")
        MainWindow.setCentralWidget(self.centralwidget)"""
        self.menubar = QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
    ############################################################
        self.menuinvestor = QMenu("Investor")
        self.investors = QMenu("Investors")
        self.payments=QMenu("Payments")
        self.investor_action=QAction("New Investor")
        self.investor_list_action=QAction("Investor List")
        self.investor_action.triggered.connect(self.newInvestor)
        self.investor_list_action.triggered.connect(self.investorList)
        self.investors.addAction(self.investor_action)
        self.investors.addAction(self.investor_list_action)
        self.current_payment_action=QAction("Current Period Payments")
        self.all_payments_action=QAction("All Payments")
        self.current_payment_action.triggered.connect(self.currentPayments)
        self.all_payments_action.triggered.connect(self.allPayments)
        self.payments.addAction(self.current_payment_action)
        self.payments.addAction(self.all_payments_action)
        self.wallets_action=QAction("Investor Wallets")
        self.wallets_action.triggered.connect(self.wallets)
        self.menuinvestor.addMenu(self.investors)
        self.menuinvestor.addMenu(self.payments)
        self.menuinvestor.addAction(self.wallets_action)
        #########################################33
        self.menufund = QMenu("Ehsan Fund")
        self.assets = QMenu("Assets")
        self.periods =QMenu("periods")
        self.basket_action=QAction("Ehsan Basket")
        self.asset_action=QAction("New Asset")
        self.asset_list_action=QAction("Asset List")
        self.basket_action.triggered.connect(self.assetBasket)
        self.asset_action.triggered.connect(self.newAsset)
        self.asset_list_action.triggered.connect(self.assetList)
        self.assets.addAction(self.asset_action)
        self.assets.addAction(self.asset_list_action)
        self.periods_action=QAction("Period List")
        self.periods_asset_action=QAction("Property")
        self.periods_action.triggered.connect(self.periodList)
        self.periods_asset_action.triggered.connect(self.periodsAssets)
        self.periods.addAction(self.periods_action)
        self.menufund.addAction(self.periods_asset_action)
        self.menufund.addAction(self.basket_action)
        self.menufund.addMenu(self.assets)
        self.menufund.addMenu(self.periods)
        self.menubar.addMenu(self.menuinvestor)
        self.menubar.addMenu(self.menufund)
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
    def  newInvestor(self):
        Form=InvestorForm()
        Form.exec_()
        Form.createNewOne.connect(self.investorPage)
    def  currentPayments(self):
        temp_widget=PaymentListForCurrentPeriod()
        self.setCentralWidget(temp_widget)
    def  allPayments(self):
        list=PaymentListForAll()
        self.setCentralWidget(list)
    def  wallets(self):
        page=WalletList()
        self.setCentralWidget(page)
    def  assetBasket(self):
        page=AssetBasketList()
        self.setCentralWidget(page)
    def  newAsset(self):
        form=AssetForm()
        form.exec_()
    def  assetList(self):  
        page=AssetList()
        self.setCentralWidget(page)
    def  periodList(self):    
        page=PeriodList()
        self.setCentralWidget(page)
    def  periodsAssets(self):
        page=AssetPeriodAmountList()
        self.setCentralWidget(page)
    def  investorPage(self):   
        page=home.EhsanHome()
        self.setCentralWidget(page)   
    def investorList(self):
            investor_page=InvestorList();
            self.setCentralWidget(investor_page)        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui=EhsanFrame()
    ehome=home.EhsanHome()
    ui.setCentralWidget(ehome)
    ui.show()
    sys.exit(app.exec_())
